name: CI Pipeline with Docker

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v4

      - name: Dar permissão de execução ao mvnw
        run: chmod +x mvnw

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Construir e iniciar contêineres em segundo plano
        run: docker-compose -f docker-compose.yml up --build -d

      - name: Verificar se os contêineres estão rodando
        run: docker ps

      - name: Executar SpotBugs
        run: ./mvnw spotbugs:check


      - name: Executar testes com Docker
        run: docker exec app ./mvnw test

      - name: Publicar resultados dos testes
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: resultados-de-testes
          path: target/surefire-reports/

      - name: Derrubar contêiner Docker após os testes
        run: docker-compose -f docker-compose.yml down
